# If true, hitting enter will execute command and tab will return to shell
# If false enter and tab will return to shell
enter_accept = false

# which style to use
# possible values: auto, full, compact
style = "compact"

# Invert UI - put search bar at the top
invert = true

# show help row, including current Atuin version, available updates, a keymap
# hint, and total amount of commands in your history.
show_help = false

# filter history recording by regexes
# regexes are unanchored - if they don't start with ^ or end with $,
# they'll match anywhere in the command.
#
# See also https://docs.rs/regex/latest/regex/#syntax
 history_filter = [
   "^tube",
   "^sideload",
   "^stream",
]
