version: '3'
tasks:
  apps:
    deps: [brew, cargo, go, krew, lua, node, ollama]
  brew:
    cmds:
      - cat home/.chezmoiscripts/run_onchange_01a_deps_brewfiles.sh.tmpl | chezmoi execute-template | zsh
  cargo:
    cmds:
      - cat home/.chezmoiscripts/run_onchange_01b_deps_cargofile.sh.tmpl | chezmoi execute-template | zsh
  go:
    cmds:
      - cat home/.chezmoiscripts/run_onchange_01c_deps_gofile.sh.tmpl | chezmoi execute-template | zsh
  extensions:
    cmds:
      - cat home/.chezmoiscripts/run_onchange_01f_deps_extensions.sh.tmpl | chezmoi execute-template | zsh
  ollama:
    cmds:
      - cat home/.chezmoiscripts/run_onchange_01d_deps_ollamafile.sh.tmpl | chezmoi execute-template | zsh
  lua:
    cmds:
      - cat home/.chezmoiscripts/run_onchange_01e_deps_luarocks.sh.tmpl | chezmoi execute-template | zsh
  node:
    cmds:
      - cat home/.chezmoiscripts/run_onchange_01g_deps_node.sh.tmpl | chezmoi execute-template | zsh
  krew:
    cmds:
      - cat home/.chezmoiscripts/run_onchange_01h_deps_krew.sh.tmpl | chezmoi execute-template | zsh
  icons:
    cmds:
      - cat home/.chezmoiscripts/run_onchange_06_customize_icons.sh.tmpl | chezmoi execute-template | zsh
  spicetify:
    cmds:
      - home/.chezmoiscripts/run_onchange_05_terminal_fish.sh
  services:
    cmds:
      - home/.chezmoiscripts/run_onchange_04_configure_services_brew.sh
