# default: 120
column_width = 120

# default: 4
indent_width = 2

# default: Tabs
indent_type = "Spaces"

# https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#requires-sorting
[sort_requires]
# default: false
enabled = true
