version: '3'
tasks:
  lua:
    cmds:
      - ln -sf sketchybarrc_lua sketchybarrc
    silent: true
  sh:
    cmds:
      - ln -sf  sketchybarrc_sh sketchybarrc
    silent: true
  toggle:
    cmds:
      - ./toggle.sh
    silent: true
