music_directory     "~/Music"
auto_update         "yes"

# State (persistent user data): XDG_DATA_HOME
playlist_directory  "~/.local/share/mpd/playlists"
db_file             "~/.local/share/mpd/database"
state_file          "~/.local/share/mpd/state"
sticker_file        "~/.local/share/mpd/sticker.sql"

# Runtime (logs, pid): XDG_STATE_HOME
log_file            "~/.local/state/mpd/log"
pid_file            "~/.local/state/mpd/pid"

bind_to_address     "127.0.0.1"
port                "6600"

audio_output {
    type            "osx"
    name            "CoreAudio"
}
