import = ["/Users/oliver/.config/alacritty/themes/gruvbox_dark.toml"]

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty-direct"

[font]
size = 20.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraLight Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraLight"

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F"
mods = "Command"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["--login", "--init-command", "/opt/homebrew/bin/sessionizer start"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "none"
option_as_alt = "Both"

[window.padding]
x = 3
y = 0
