import = ["/Users/oliver/.config/alacritty/themes/active.toml"]

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty-direct"

[font]
size = 22.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraLight Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraLight"

[font.offset]
x = 0
y = 2

# forward Ctrl++Tab (get's "eaten by alacritty")
[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

# forward Ctrl+Shift+Tab (get's "eaten by alacritty")
[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F"
mods = "Command"

# prevent accidental new window
[[keyboard.bindings]]
action = "None"
key = "N"
mods = "Command"

# prevent accidental new tab
[[keyboard.bindings]]
action = "None"
key = "T"
mods = "Command"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = [
  "--login",
  "--init-command",
  "/opt/homebrew/bin/sessionizer start; tmux attach -t default",
]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "none"
option_as_alt = "Both"

[window.padding]
x = 3
y = 0
