version: '3'
tasks:
  dark:
    cmds:
      - ./appearance.sh dark
    silent: true
  light:
    cmds:
      - ./appearance.sh light
    silent: true
  toggle:
    cmds:
      - ./appearance.sh toggle
    silent: true
