[[journals]]

[[journals.default]]
path = "$HOME/Obsidian/memex/10 Journals/Personal"
extension = "md"

[[journals.work]]
path = "$HOME/Obsidian/memex/10 Journals/10 Journals/Work"
extension = "md"

[sketchybar]
path = "/opt/homebrew/bin/sketchybar"
event_task = "mission_task"
event_focus = "mission_focus"
