prSections:
- title: Needs My Review
  filters: is:open review-requested:@me
- title: My Pull Requests
  filters: is:open author:@me
- title: Involved
  filters: is:open involves:@me -author:@me
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      repo:
        grow: true
        width: 25
        hidden: false
    issues:
      repo:
        grow: true
        width: 25
        hidden: false
keybindings:
  issues: []
  prs: []
repoPaths: {}
theme:
  ui:
    table:
      showSeparator: true
pager:
  diff: ""
