# Sample config
#   https://github.com/meli/meli/blob/master/meli/docs/samples/sample-config.toml

# Flags
# meli supports the basic `maildir` flags: 
#  - passed, 
#  - replied,
#  - seen, 
#  - trashed, 
#  - draft and 
#  - flagged. 
#
# Flags can be searched with `flags:` prefix in a search query, 
# and can be modified by
#    flag set FLAG
#    flag unset FLAG

# Tags
# meli supports tagging in notmuch and IMAP/JMAP backends. 
# Tags can be searched with the `tags:` prefix in a search query,
# and can be modified by
#    tag add TAG
#    tag remove TAG

[accounts.personal]
identity     = "oliver.schrenk@gmail.com"
display_name = "Oliver Schrenk"

format                  = "imap"
server_hostname         = 'imap.gmail.com'
server_password_command = "~/.config/meli/password_command.sh"
server_username         = "oliver.schrenk@gmail.com"
server_port             = "993"
use_oauth2              = true

root_mailbox = '[Gmail]'

# all: ["*"]
subscribed_mailboxes = ["INBOX"]

## Gmail auto saves sent mail to Sent folder, so don't duplicate the effort:
composing.store_sent_mail = false
send_mail                 = { hostname = "smtp.gmail.com", port = 587, auth = { type = "xoauth2", token_command = "...", require_auth = true }, security = { type = "STARTTLS" } }

[accounts.personal.mailboxes]
"History" = { collapsed = true }

[listing]
# plain|threaded|compact|conversations
index_style           = "compact"
recent_dates          = true
relative_list_indices = false
relative_menu_indices = false
sidebar_ratio         = 75
unseen_flag           = "␣"

[shortcuts.general]
enter_command_mode = ":"
quit               = "q"
toggle_help        = "?"

[shortcuts.listing]
focus_left  = 'h'
focus_right = 'l'
open_entry  = "Enter"
exit_entry  = 'Esc'
refresh     = 'R'     # default: F5

[shortcuts."envelope-view"]
return_to_normal_view = 'r' # default: r


[terminal]
theme         = "gruvbox"
ascii_drawing = true
